export const countries = [
  { code: 'AF', name_es: 'afganistán', name_en: 'afghanistan' },
  { code: 'AL', name_es: 'albania', name_en: 'albania' },
  { code: 'DZ', name_es: 'argelia', name_en: 'algeria' },
  { code: 'AD', name_es: 'andorra', name_en: 'andorra' },
  { code: 'AO', name_es: 'angola', name_en: 'angola' },
  { code: 'AG', name_es: 'antigua y barbuda', name_en: 'antigua and barbuda' },
  { code: 'AR', name_es: 'argentina', name_en: 'argentina' },
  { code: 'AM', name_es: 'armenia', name_en: 'armenia' },
  { code: 'AU', name_es: 'australia', name_en: 'australia' },
  { code: 'AT', name_es: 'austria', name_en: 'austria' },
  { code: 'AZ', name_es: 'azerbaiyán', name_en: 'azerbaijan' },
  { code: 'BS', name_es: 'bahamas', name_en: 'bahamas' },
  { code: 'BH', name_es: 'baréin', name_en: 'bahrain' },
  { code: 'BD', name_es: 'bangladés', name_en: 'bangladesh' },
  { code: 'BB', name_es: 'barbados', name_en: 'barbados' },
  { code: 'BY', name_es: 'bielorrusia', name_en: 'belarus' },
  { code: 'BE', name_es: 'bélgica', name_en: 'belgium' },
  { code: 'BZ', name_es: 'belice', name_en: 'belize' },
  { code: 'BJ', name_es: 'benín', name_en: 'benin' },
  { code: 'BT', name_es: 'bután', name_en: 'bhutan' },
  { code: 'BO', name_es: 'bolivia', name_en: 'bolivia' },
  { code: 'BA', name_es: 'bosnia y herzegovina', name_en: 'bosnia and herzegovina' },
  { code: 'BW', name_es: 'botsuana', name_en: 'botswana' },
  { code: 'BR', name_es: 'brasil', name_en: 'brazil' },
  { code: 'BN', name_es: 'brunéi', name_en: 'brunei' },
  { code: 'BG', name_es: 'bulgaria', name_en: 'bulgaria' },
  { code: 'BF', name_es: 'burkina faso', name_en: 'burkina faso' },
  { code: 'BI', name_es: 'burundi', name_en: 'burundi' },
  { code: 'CV', name_es: 'cabo verde', name_en: 'cape verde' },
  { code: 'KH', name_es: 'camboya', name_en: 'cambodia' },
  { code: 'CM', name_es: 'camerún', name_en: 'cameroon' },
  { code: 'CA', name_es: 'canadá', name_en: 'canada' },
  { code: 'CF', name_es: 'república centroafricana', name_en: 'central african republic' },
  { code: 'TD', name_es: 'chad', name_en: 'chad' },
  { code: 'CL', name_es: 'chile', name_en: 'chile' },
  { code: 'CN', name_es: 'china', name_en: 'china' },
  { code: 'CO', name_es: 'colombia', name_en: 'colombia' },
  { code: 'KM', name_es: 'comoras', name_en: 'comoros' },
  { code: 'CG', name_es: 'república del congo', name_en: 'republic of the congo' },
  { code: 'CD', name_es: 'república democrática del congo', name_en: 'democratic republic of the congo' },
  { code: 'CR', name_es: 'costa rica', name_en: 'costa rica' },
  { code: 'CI', name_es: 'costa de marfil', name_en: 'ivory coast' },
  { code: 'HR', name_es: 'croacia', name_en: 'croatia' },
  { code: 'CU', name_es: 'cuba', name_en: 'cuba' },
  { code: 'CY', name_es: 'chipre', name_en: 'cyprus' },
  { code: 'CZ', name_es: 'república checa', name_en: 'czech republic' },
  { code: 'DK', name_es: 'dinamarca', name_en: 'denmark' },
  { code: 'DJ', name_es: 'yibuti', name_en: 'djibouti' },
  { code: 'DM', name_es: 'dominica', name_en: 'dominica' },
  { code: 'DO', name_es: 'república dominicana', name_en: 'dominican republic' },
  { code: 'EC', name_es: 'ecuador', name_en: 'ecuador' },
  { code: 'EG', name_es: 'egipto', name_en: 'egypt' },
  { code: 'SV', name_es: 'el salvador', name_en: 'el salvador' },
  { code: 'GQ', name_es: 'guinea ecuatorial', name_en: 'equatorial guinea' },
  { code: 'ER', name_es: 'eritrea', name_en: 'eritrea' },
  { code: 'EE', name_es: 'estonia', name_en: 'estonia' },
  { code: 'SZ', name_es: 'esuatini', name_en: 'eswatini' },
  { code: 'ET', name_es: 'etiopía', name_en: 'ethiopia' },
  { code: 'FJ', name_es: 'fiyi', name_en: 'fiji' },
  { code: 'FI', name_es: 'finlandia', name_en: 'finland' },
  { code: 'FR', name_es: 'francia', name_en: 'france' },
  { code: 'GA', name_es: 'gabón', name_en: 'gabon' },
  { code: 'GM', name_es: 'gambia', name_en: 'gambia' },
  { code: 'GE', name_es: 'georgia', name_en: 'georgia' },
  { code: 'DE', name_es: 'alemania', name_en: 'germany' },
  { code: 'GH', name_es: 'ghana', name_en: 'ghana' },
  { code: 'GR', name_es: 'grecia', name_en: 'greece' },
  { code: 'GD', name_es: 'granada', name_en: 'grenada' },
  { code: 'GT', name_es: 'guatemala', name_en: 'guatemala' },
  { code: 'GN', name_es: 'guinea', name_en: 'guinea' },
  { code: 'GW', name_es: 'guinea-bisáu', name_en: 'guinea-bissau' },
  { code: 'GY', name_es: 'guyana', name_en: 'guyana' },
  { code: 'HT', name_es: 'haití', name_en: 'haiti' },
  { code: 'HN', name_es: 'honduras', name_en: 'honduras' },
  { code: 'HU', name_es: 'hungría', name_en: 'hungary' },
  { code: 'IS', name_es: 'islandia', name_en: 'iceland' },
  { code: 'IN', name_es: 'india', name_en: 'india' },
  { code: 'ID', name_es: 'indonesia', name_en: 'indonesia' },
  { code: 'IR', name_es: 'irán', name_en: 'iran' },
  { code: 'IQ', name_es: 'irak', name_en: 'iraq' },
  { code: 'IE', name_es: 'irlanda', name_en: 'ireland' },
  { code: 'IL', name_es: 'israel', name_en: 'israel' },
  { code: 'IT', name_es: 'italia', name_en: 'italy' },
  { code: 'JM', name_es: 'jamaica', name_en: 'jamaica' },
  { code: 'JP', name_es: 'japón', name_en: 'japan' },
  { code: 'JO', name_es: 'jordania', name_en: 'jordan' },
  { code: 'KZ', name_es: 'kazajistán', name_en: 'kazakhstan' },
  { code: 'KE', name_es: 'kenia', name_en: 'kenya' },
  { code: 'KI', name_es: 'kiribati', name_en: 'kiribati' },
  { code: 'KP', name_es: 'corea del norte', name_en: 'north korea' },
  { code: 'KR', name_es: 'corea del sur', name_en: 'south korea' },
  { code: 'KW', name_es: 'kuwait', name_en: 'kuwait' },
  { code: 'KG', name_es: 'kirguistán', name_en: 'kyrgyzstan' },
  { code: 'LA', name_es: 'laos', name_en: 'laos' },
  { code: 'LV', name_es: 'letonia', name_en: 'latvia' },
  { code: 'LB', name_es: 'líbano', name_en: 'lebanon' },
  { code: 'LS', name_es: 'lesoto', name_en: 'lesotho' },
  { code: 'LR', name_es: 'liberia', name_en: 'liberia' },
  { code: 'LY', name_es: 'libia', name_en: 'libya' },
  { code: 'LI', name_es: 'liechtenstein', name_en: 'liechtenstein' },
  { code: 'LT', name_es: 'lituania', name_en: 'lithuania' },
  { code: 'LU', name_es: 'luxemburgo', name_en: 'luxembourg' },
  { code: 'MG', name_es: 'madagascar', name_en: 'madagascar' },
  { code: 'MW', name_es: 'malaui', name_en: 'malawi' },
  { code: 'MY', name_es: 'malasia', name_en: 'malaysia' },
  { code: 'MV', name_es: 'maldivas', name_en: 'maldives' },
  { code: 'ML', name_es: 'malí', name_en: 'mali' },
  { code: 'MT', name_es: 'malta', name_en: 'malta' },
  { code: 'MH', name_es: 'islas marshall', name_en: 'marshall islands' },
  { code: 'MR', name_es: 'mauritania', name_en: 'mauritania' },
  { code: 'MU', name_es: 'mauricio', name_en: 'mauritius' },
  { code: 'MX', name_es: 'méxico', name_en: 'mexico' },
  { code: 'FM', name_es: 'micronesia', name_en: 'micronesia' },
  { code: 'MD', name_es: 'moldavia', name_en: 'moldova' },
  { code: 'MC', name_es: 'mónaco', name_en: 'monaco' },
  { code: 'MN', name_es: 'mongolia', name_en: 'mongolia' },
  { code: 'ME', name_es: 'montenegro', name_en: 'montenegro' },
  { code: 'MA', name_es: 'marruecos', name_en: 'morocco' },
  { code: 'MZ', name_es: 'mozambique', name_en: 'mozambique' },
  { code: 'MM', name_es: 'myanmar', name_en: 'myanmar' },
  { code: 'NA', name_es: 'namibia', name_en: 'namibia' },
  { code: 'NR', name_es: 'nauru', name_en: 'nauru' },
  { code: 'NP', name_es: 'nepal', name_en: 'nepal' },
  { code: 'NL', name_es: 'países bajos', name_en: 'netherlands' },
  { code: 'NZ', name_es: 'nueva zelanda', name_en: 'new zealand' },
  { code: 'NI', name_es: 'nicaragua', name_en: 'nicaragua' },
  { code: 'NE', name_es: 'níger', name_en: 'niger' },
  { code: 'NG', name_es: 'nigeria', name_en: 'nigeria' },
  { code: 'MK', name_es: 'macedonia del norte', name_en: 'north macedonia' },
  { code: 'NO', name_es: 'noruega', name_en: 'norway' },
  { code: 'OM', name_es: 'omán', name_en: 'oman' },
  { code: 'PK', name_es: 'pakistán', name_en: 'pakistan' },
  { code: 'PW', name_es: 'palaos', name_en: 'palau' },
  { code: 'PA', name_es: 'panamá', name_en: 'panama' },
  { code: 'PG', name_es: 'papúa nueva guinea', name_en: 'papua new guinea' },
  { code: 'PY', name_es: 'paraguay', name_en: 'paraguay' },
  { code: 'PE', name_es: 'perú', name_en: 'peru' },
  { code: 'PH', name_es: 'filipinas', name_en: 'philippines' },
  { code: 'PL', name_es: 'polonia', name_en: 'poland' },
  { code: 'PT', name_es: 'portugal', name_en: 'portugal' },
  { code: 'QA', name_es: 'catar', name_en: 'qatar' },
  { code: 'RO', name_es: 'rumanía', name_en: 'romania' },
  { code: 'RU', name_es: 'rusia', name_en: 'russia' },
  { code: 'RW', name_es: 'ruanda', name_en: 'rwanda' },
  { code: 'KN', name_es: 'san cristóbal y nieves', name_en: 'saint kitts and nevis' },
  { code: 'LC', name_es: 'santa lucía', name_en: 'saint lucia' },
  { code: 'VC', name_es: 'san vicente y las granadinas', name_en: 'saint vincent and the grenadines' },
  { code: 'WS', name_es: 'samoa', name_en: 'samoa' },
  { code: 'SM', name_es: 'san marino', name_en: 'san marino' },
  { code: 'ST', name_es: 'santo tomé y príncipe', name_en: 'sao tome and principe' },
  { code: 'SA', name_es: 'arabia saudí', name_en: 'saudi arabia' },
  { code: 'SN', name_es: 'senegal', name_en: 'senegal' },
  { code: 'RS', name_es: 'serbia', name_en: 'serbia' },
  { code: 'SC', name_es: 'seychelles', name_en: 'seychelles' },
  { code: 'SL', name_es: 'sierra leona', name_en: 'sierra leone' },
  { code: 'SG', name_es: 'singapur', name_en: 'singapore' },
  { code: 'SK', name_es: 'eslovaquia', name_en: 'slovakia' },
  { code: 'SI', name_es: 'eslovenia', name_en: 'slovenia' },
  { code: 'SB', name_es: 'islas salomón', name_en: 'solomon islands' },
  { code: 'SO', name_es: 'somalia', name_en: 'somalia' },
  { code: 'ZA', name_es: 'sudáfrica', name_en: 'south africa' },
  { code: 'SS', name_es: 'sudán del sur', name_en: 'south sudan' },
  { code: 'ES', name_es: 'españa', name_en: 'spain' },
  { code: 'LK', name_es: 'sri lanka', name_en: 'sri lanka' },
  { code: 'SD', name_es: 'sudán', name_en: 'sudan' },
  { code: 'SR', name_es: 'surinam', name_en: 'suriname' },
  { code: 'SE', name_es: 'suecia', name_en: 'sweden' },
  { code: 'CH', name_es: 'suiza', name_en: 'switzerland' },
  { code: 'SY', name_es: 'siria', name_en: 'syria' },
  { code: 'TW', name_es: 'taiwán', name_en: 'taiwan' },
  { code: 'TJ', name_es: 'tayikistán', name_en: 'tajikistan' },
  { code: 'TZ', name_es: 'tanzania', name_en: 'tanzania' },
  { code: 'TH', name_es: 'tailandia', name_en: 'thailand' },
  { code: 'TL', name_es: 'timor oriental', name_en: 'east timor' },
  { code: 'TG', name_es: 'togo', name_en: 'togo' },
  { code: 'TO', name_es: 'tonga', name_en: 'tonga' },
  { code: 'TT', name_es: 'trinidad y tobago', name_en: 'trinidad and tobago' },
  { code: 'TN', name_es: 'túnez', name_en: 'tunisia' },
  { code: 'TR', name_es: 'turquía', name_en: 'turkey' },
  { code: 'TM', name_es: 'turkmenistán', name_en: 'turkmenistan' },
  { code: 'TV', name_es: 'tuvalu', name_en: 'tuvalu' },
  { code: 'UG', name_es: 'uganda', name_en: 'uganda' },
  { code: 'UA', name_es: 'ucrania', name_en: 'ukraine' },
  { code: 'AE', name_es: 'emiratos árabes unidos', name_en: 'united arab emirates' },
  { code: 'GB', name_es: 'reino unido', name_en: 'united kingdom' },
  { code: 'US', name_es: 'estados unidos', name_en: 'united states' },
  { code: 'UY', name_es: 'uruguay', name_en: 'uruguay' },
  { code: 'UZ', name_es: 'uzbekistán', name_en: 'uzbekistan' },
  { code: 'VU', name_es: 'vanuatu', name_en: 'vanuatu' },
  { code: 'VA', name_es: 'vaticano', name_en: 'vatican city' },
  { code: 'VE', name_es: 'venezuela', name_en: 'venezuela' },
  { code: 'VN', name_es: 'vietnam', name_en: 'vietnam' },
  { code: 'YE', name_es: 'yemen', name_en: 'yemen' },
  { code: 'ZM', name_es: 'zambia', name_en: 'zambia' },
  { code: 'ZW', name_es: 'zimbabue', name_en: 'zimbabwe' },
]
 


