export const countriesData = {
  AF: { capital: 'Kabul', continent: 'Asia', population: '40M', area: '652.230 km²' },
  AL: { capital: 'Tirana', continent: 'Europa', population: '2.8M', area: '28.748 km²' },
  DZ: { capital: 'Argel', continent: 'África', population: '44M', area: '2.381.741 km²' },
  AD: { capital: 'Andorra la Vella', continent: 'Europa', population: '77K', area: '468 km²' },
  AO: { capital: 'Luanda', continent: 'África', population: '34M', area: '1.246.700 km²' },
  AG: { capital: 'Saint John\'s', continent: 'América', population: '93K', area: '442 km²' },
  AR: { capital: 'Buenos Aires', continent: 'América', population: '45M', area: '2.780.400 km²' },
  AM: { capital: 'Ereván', continent: 'Asia', population: '3M', area: '29.743 km²' },
  AU: { capital: 'Canberra', continent: 'Oceanía', population: '26M', area: '7.692.024 km²' },
  AT: { capital: 'Viena', continent: 'Europa', population: '9M', area: '83.871 km²' },
  AZ: { capital: 'Bakú', continent: 'Asia', population: '10M', area: '86.600 km²' },
  BS: { capital: 'Nasáu', continent: 'América', population: '393K', area: '13.943 km²' },
  BH: { capital: 'Manama', continent: 'Asia', population: '1.7M', area: '778 km²' },
  BD: { capital: 'Daca', continent: 'Asia', population: '167M', area: '147.570 km²' },
  BB: { capital: 'Bridgetown', continent: 'América', population: '288K', area: '430 km²' },
  BY: { capital: 'Minsk', continent: 'Europa', population: '9.4M', area: '207.600 km²' },
  BE: { capital: 'Bruselas', continent: 'Europa', population: '11.5M', area: '30.528 km²' },
  BZ: { capital: 'Belmopán', continent: 'América', population: '398K', area: '22.966 km²' },
  BJ: { capital: 'Porto-Novo', continent: 'África', population: '12M', area: '114.763 km²' },
  BT: { capital: 'Timbu', continent: 'Asia', population: '772K', area: '38.394 km²' },
  BO: { capital: 'Sucre', continent: 'América', population: '12M', area: '1.098.581 km²' },
  BA: { capital: 'Sarajevo', continent: 'Europa', population: '3.3M', area: '51.197 km²' },
  BW: { capital: 'Gaborone', continent: 'África', population: '2.4M', area: '581.730 km²' },
  BR: { capital: 'Brasilia', continent: 'América', population: '215M', area: '8.515.767 km²' },
  BN: { capital: 'Bandar Seri Begawan', continent: 'Asia', population: '441K', area: '5.765 km²' },
  BG: { capital: 'Sofía', continent: 'Europa', population: '6.5M', area: '110.879 km²' },
  BF: { capital: 'Uagadugú', continent: 'África', population: '22M', area: '274.222 km²' },
  BI: { capital: 'Gitega', continent: 'África', population: '12M', area: '27.834 km²' },
  CV: { capital: 'Praia', continent: 'África', population: '561K', area: '4.033 km²' },
  KH: { capital: 'Nom Pen', continent: 'Asia', population: '17M', area: '181.035 km²' },
  CM: { capital: 'Yaundé', continent: 'África', population: '27M', area: '475.442 km²' },
  CA: { capital: 'Ottawa', continent: 'América', population: '38M', area: '9.984.670 km²' },
  CF: { capital: 'Bangui', continent: 'África', population: '5M', area: '622.984 km²' },
  TD: { capital: 'Yamena', continent: 'África', population: '17M', area: '1.284.000 km²' },
  CL: { capital: 'Santiago', continent: 'América', population: '19M', area: '756.102 km²' },
  CN: { capital: 'Pekín', continent: 'Asia', population: '1.400M', area: '9.596.960 km²' },
  CO: { capital: 'Bogotá', continent: 'América', population: '51M', area: '1.141.748 km²' },
  KM: { capital: 'Moroni', continent: 'África', population: '888K', area: '2.235 km²' },
  CG: { capital: 'Brazzaville', continent: 'África', population: '5.8M', area: '342.000 km²' },
  CD: { capital: 'Kinshasa', continent: 'África', population: '100M', area: '2.344.858 km²' },
  CR: { capital: 'San José', continent: 'América', population: '5.2M', area: '51.100 km²' },
  CI: { capital: 'Yamusukro', continent: 'África', population: '27M', area: '322.463 km²' },
  HR: { capital: 'Zagreb', continent: 'Europa', population: '3.9M', area: '56.594 km²' },
  CU: { capital: 'La Habana', continent: 'América', population: '11M', area: '109.884 km²' },
  CY: { capital: 'Nicosia', continent: 'Europa', population: '1.2M', area: '9.251 km²' },
  CZ: { capital: 'Praga', continent: 'Europa', population: '10.9M', area: '78.866 km²' },
  DK: { capital: 'Copenhague', continent: 'Europa', population: '5.9M', area: '43.094 km²' },
  DJ: { capital: 'Yibuti', continent: 'África', population: '988K', area: '23.200 km²' },
  DM: { capital: 'Roseau', continent: 'América', population: '72K', area: '751 km²' },
  DO: { capital: 'Santo Domingo', continent: 'América', population: '11M', area: '48.671 km²' },
  EC: { capital: 'Quito', continent: 'América', population: '18M', area: '283.561 km²' },
  EG: { capital: 'El Cairo', continent: 'África', population: '104M', area: '1.001.450 km²' },
  SV: { capital: 'San Salvador', continent: 'América', population: '6.5M', area: '21.041 km²' },
  GQ: { capital: 'Malabo', continent: 'África', population: '1.5M', area: '28.051 km²' },
  ER: { capital: 'Asmara', continent: 'África', population: '3.5M', area: '117.600 km²' },
  EE: { capital: 'Tallin', continent: 'Europa', population: '1.3M', area: '45.228 km²' },
  SZ: { capital: 'Mbabane', continent: 'África', population: '1.2M', area: '17.364 km²' },
  ET: { capital: 'Adís Abeba', continent: 'África', population: '120M', area: '1.104.300 km²' },
  FJ: { capital: 'Suva', continent: 'Oceanía', population: '930K', area: '18.274 km²' },
  FI: { capital: 'Helsinki', continent: 'Europa', population: '5.5M', area: '338.424 km²' },
  FR: { capital: 'París', continent: 'Europa', population: '68M', area: '551.695 km²' },
  GA: { capital: 'Libreville', continent: 'África', population: '2.3M', area: '267.668 km²' },
  GM: { capital: 'Banjul', continent: 'África', population: '2.5M', area: '11.295 km²' },
  GE: { capital: 'Tiflis', continent: 'Asia', population: '3.7M', area: '69.700 km²' },
  DE: { capital: 'Berlín', continent: 'Europa', population: '83M', area: '357.114 km²' },
  GH: { capital: 'Acra', continent: 'África', population: '32M', area: '238.533 km²' },
  GR: { capital: 'Atenas', continent: 'Europa', population: '10.7M', area: '131.957 km²' },
  GD: { capital: 'Saint George\'s', continent: 'América', population: '113K', area: '344 km²' },
  GT: { capital: 'Ciudad de Guatemala', continent: 'América', population: '17M', area: '108.889 km²' },
  GN: { capital: 'Conakri', continent: 'África', population: '13M', area: '245.857 km²' },
  GW: { capital: 'Bisáu', continent: 'África', population: '2M', area: '36.125 km²' },
  GY: { capital: 'Georgetown', continent: 'América', population: '787K', area: '214.969 km²' },
  HT: { capital: 'Puerto Príncipe', continent: 'América', population: '11M', area: '27.750 km²' },
  HN: { capital: 'Tegucigalpa', continent: 'América', population: '10M', area: '112.492 km²' },
  HU: { capital: 'Budapest', continent: 'Europa', population: '9.7M', area: '93.028 km²' },
  IS: { capital: 'Reikiavik', continent: 'Europa', population: '372K', area: '103.000 km²' },
  IN: { capital: 'Nueva Delhi', continent: 'Asia', population: '1.400M', area: '3.287.263 km²' },
  ID: { capital: 'Yakarta', continent: 'Asia', population: '277M', area: '1.904.569 km²' },
  IR: { capital: 'Teherán', continent: 'Asia', population: '87M', area: '1.648.195 km²' },
  IQ: { capital: 'Bagdad', continent: 'Asia', population: '42M', area: '438.317 km²' },
  IE: { capital: 'Dublín', continent: 'Europa', population: '5M', area: '70.273 km²' },
  IL: { capital: 'Jerusalén', continent: 'Asia', population: '9.5M', area: '20.770 km²' },
  IT: { capital: 'Roma', continent: 'Europa', population: '60M', area: '301.340 km²' },
  JM: { capital: 'Kingston', continent: 'América', population: '3M', area: '10.991 km²' },
  JP: { capital: 'Tokio', continent: 'Asia', population: '125M', area: '377.930 km²' },
  JO: { capital: 'Ammán', continent: 'Asia', population: '10M', area: '89.342 km²' },
  KZ: { capital: 'Astana', continent: 'Asia', population: '19M', area: '2.724.900 km²' },
  KE: { capital: 'Nairobi', continent: 'África', population: '54M', area: '580.367 km²' },
  KI: { capital: 'Tarawa del Sur', continent: 'Oceanía', population: '119K', area: '811 km²' },
  KP: { capital: 'Pionyang', continent: 'Asia', population: '26M', area: '120.538 km²' },
  KR: { capital: 'Seúl', continent: 'Asia', population: '52M', area: '100.210 km²' },
  KW: { capital: 'Kuwait', continent: 'Asia', population: '4.3M', area: '17.818 km²' },
  KG: { capital: 'Biskek', continent: 'Asia', population: '6.7M', area: '199.951 km²' },
  LA: { capital: 'Vientián', continent: 'Asia', population: '7.4M', area: '236.800 km²' },
  LV: { capital: 'Riga', continent: 'Europa', population: '1.8M', area: '64.589 km²' },
  LB: { capital: 'Beirut', continent: 'Asia', population: '6.8M', area: '10.452 km²' },
  LS: { capital: 'Maseru', continent: 'África', population: '2.2M', area: '30.355 km²' },
  LR: { capital: 'Monrovia', continent: 'África', population: '5.3M', area: '111.369 km²' },
  LY: { capital: 'Trípoli', continent: 'África', population: '7M', area: '1.759.540 km²' },
  LI: { capital: 'Vaduz', continent: 'Europa', population: '38K', area: '160 km²' },
  LT: { capital: 'Vilna', continent: 'Europa', population: '2.8M', area: '65.300 km²' },
  LU: { capital: 'Luxemburgo', continent: 'Europa', population: '645K', area: '2.586 km²' },
  MG: { capital: 'Antananarivo', continent: 'África', population: '28M', area: '587.041 km²' },
  MW: { capital: 'Lilongüe', continent: 'África', population: '20M', area: '118.484 km²' },
  MY: { capital: 'Kuala Lumpur', continent: 'Asia', population: '33M', area: '329.847 km²' },
  MV: { capital: 'Malé', continent: 'Asia', population: '541K', area: '298 km²' },
  ML: { capital: 'Bamako', continent: 'África', population: '22M', area: '1.240.192 km²' },
  MT: { capital: 'La Valeta', continent: 'Europa', population: '514K', area: '316 km²' },
  MH: { capital: 'Majuro', continent: 'Oceanía', population: '42K', area: '181 km²' },
  MR: { capital: 'Nuakchot', continent: 'África', population: '4.5M', area: '1.030.700 km²' },
  MU: { capital: 'Port Louis', continent: 'África', population: '1.3M', area: '2.040 km²' },
  MX: { capital: 'Ciudad de México', continent: 'América', population: '130M', area: '1.964.375 km²' },
  FM: { capital: 'Palikir', continent: 'Oceanía', population: '115K', area: '702 km²' },
  MD: { capital: 'Chisináu', continent: 'Europa', population: '2.6M', area: '33.851 km²' },
  MC: { capital: 'Mónaco', continent: 'Europa', population: '39K', area: '2 km²' },
  MN: { capital: 'Ulán Bator', continent: 'Asia', population: '3.3M', area: '1.564.116 km²' },
  ME: { capital: 'Podgorica', continent: 'Europa', population: '621K', area: '13.812 km²' },
  MA: { capital: 'Rabat', continent: 'África', population: '37M', area: '446.550 km²' },
  MZ: { capital: 'Maputo', continent: 'África', population: '32M', area: '801.590 km²' },
  MM: { capital: 'Naipyidó', continent: 'Asia', population: '54M', area: '676.578 km²' },
  NA: { capital: 'Windhoek', continent: 'África', population: '2.6M', area: '824.292 km²' },
  NR: { capital: 'Yaren', continent: 'Oceanía', population: '10K', area: '21 km²' },
  NP: { capital: 'Katmandú', continent: 'Asia', population: '30M', area: '147.181 km²' },
  NL: { capital: 'Ámsterdam', continent: 'Europa', population: '17.6M', area: '41.543 km²' },
  NZ: { capital: 'Wellington', continent: 'Oceanía', population: '5.1M', area: '270.467 km²' },
  NI: { capital: 'Managua', continent: 'América', population: '6.9M', area: '130.370 km²' },
  NE: { capital: 'Niamey', continent: 'África', population: '25M', area: '1.267.000 km²' },
  NG: { capital: 'Abuya', continent: 'África', population: '218M', area: '923.768 km²' },
  MK: { capital: 'Skopie', continent: 'Europa', population: '2.1M', area: '25.713 km²' },
  NO: { capital: 'Oslo', continent: 'Europa', population: '5.4M', area: '323.802 km²' },
  OM: { capital: 'Mascate', continent: 'Asia', population: '4.5M', area: '309.500 km²' },
  PK: { capital: 'Islamabad', continent: 'Asia', population: '231M', area: '881.913 km²' },
  PW: { capital: 'Ngerulmud', continent: 'Oceanía', population: '18K', area: '459 km²' },
  PA: { capital: 'Ciudad de Panamá', continent: 'América', population: '4.4M', area: '75.417 km²' },
  PG: { capital: 'Port Moresby', continent: 'Oceanía', population: '10M', area: '462.840 km²' },
  PY: { capital: 'Asunción', continent: 'América', population: '7.4M', area: '406.752 km²' },
  PE: { capital: 'Lima', continent: 'América', population: '33M', area: '1.285.216 km²' },
  PH: { capital: 'Manila', continent: 'Asia', population: '114M', area: '300.000 km²' },
  PL: { capital: 'Varsovia', continent: 'Europa', population: '38M', area: '312.679 km²' },
  PT: { capital: 'Lisboa', continent: 'Europa', population: '10.3M', area: '92.212 km²' },
  QA: { capital: 'Doha', continent: 'Asia', population: '2.9M', area: '11.586 km²' },
  RO: { capital: 'Bucarest', continent: 'Europa', population: '19M', area: '238.397 km²' },
  RU: { capital: 'Moscú', continent: 'Europa/Asia', population: '144M', area: '17.098.242 km²' },
  RW: { capital: 'Kigali', continent: 'África', population: '13M', area: '26.338 km²' },
  KN: { capital: 'Basseterre', continent: 'América', population: '53K', area: '261 km²' },
  LC: { capital: 'Castries', continent: 'América', population: '184K', area: '616 km²' },
  VC: { capital: 'Kingstown', continent: 'América', population: '111K', area: '389 km²' },
  WS: { capital: 'Apia', continent: 'Oceanía', population: '218K', area: '2.842 km²' },
  SM: { capital: 'San Marino', continent: 'Europa', population: '34K', area: '61 km²' },
  ST: { capital: 'Santo Tomé', continent: 'África', population: '223K', area: '964 km²' },
  SA: { capital: 'Riad', continent: 'Asia', population: '35M', area: '2.149.690 km²' },
  SN: { capital: 'Dakar', continent: 'África', population: '17M', area: '196.722 km²' },
  RS: { capital: 'Belgrado', continent: 'Europa', population: '6.8M', area: '77.474 km²' },
  SC: { capital: 'Victoria', continent: 'África', population: '98K', area: '455 km²' },
  SL: { capital: 'Freetown', continent: 'África', population: '8.2M', area: '71.740 km²' },
  SG: { capital: 'Singapur', continent: 'Asia', population: '5.9M', area: '728 km²' },
  SK: { capital: 'Bratislava', continent: 'Europa', population: '5.5M', area: '49.035 km²' },
  SI: { capital: 'Liubliana', continent: 'Europa', population: '2.1M', area: '20.273 km²' },
  SB: { capital: 'Honiara', continent: 'Oceanía', population: '720K', area: '28.896 km²' },
  SO: { capital: 'Mogadiscio', continent: 'África', population: '17M', area: '637.657 km²' },
  ZA: { capital: 'Pretoria', continent: 'África', population: '60M', area: '1.219.090 km²' },
  SS: { capital: 'Yuba', continent: 'África', population: '11M', area: '619.745 km²' },
  ES: { capital: 'Madrid', continent: 'Europa', population: '47M', area: '505.990 km²' },
  LK: { capital: 'Sri Jayawardenepura Kotte', continent: 'Asia', population: '22M', area: '65.610 km²' },
  SD: { capital: 'Jartum', continent: 'África', population: '46M', area: '1.861.484 km²' },
  SR: { capital: 'Paramaribo', continent: 'América', population: '618K', area: '163.820 km²' },
  SE: { capital: 'Estocolmo', continent: 'Europa', population: '10.4M', area: '450.295 km²' },
  CH: { capital: 'Berna', continent: 'Europa', population: '8.7M', area: '41.285 km²' },
  SY: { capital: 'Damasco', continent: 'Asia', population: '22M', area: '185.180 km²' },
  TW: { capital: 'Taipéi', continent: 'Asia', population: '23M', area: '36.193 km²' },
  TJ: { capital: 'Dusambé', continent: 'Asia', population: '10M', area: '143.100 km²' },
  TZ: { capital: 'Dodoma', continent: 'África', population: '63M', area: '945.087 km²' },
  TH: { capital: 'Bangkok', continent: 'Asia', population: '72M', area: '513.120 km²' },
  TL: { capital: 'Dili', continent: 'Asia', population: '1.3M', area: '14.874 km²' },
  TG: { capital: 'Lomé', continent: 'África', population: '8.6M', area: '56.785 km²' },
  TO: { capital: 'Nukualofa', continent: 'Oceanía', population: '100K', area: '747 km²' },
  TT: { capital: 'Puerto España', continent: 'América', population: '1.4M', area: '5.130 km²' },
  TN: { capital: 'Túnez', continent: 'África', population: '12M', area: '163.610 km²' },
  TR: { capital: 'Ankara', continent: 'Asia/Europa', population: '85M', area: '783.562 km²' },
  TM: { capital: 'Asjabad', continent: 'Asia', population: '6M', area: '488.100 km²' },
  TV: { capital: 'Funafuti', continent: 'Oceanía', population: '11K', area: '26 km²' },
  UG: { capital: 'Kampala', continent: 'África', population: '48M', area: '241.038 km²' },
  UA: { capital: 'Kiev', continent: 'Europa', population: '44M', area: '603.550 km²' },
  AE: { capital: 'Abu Dabi', continent: 'Asia', population: '10M', area: '83.600 km²' },
  GB: { capital: 'Londres', continent: 'Europa', population: '67M', area: '242.495 km²' },
  US: { capital: 'Washington D.C.', continent: 'América', population: '331M', area: '9.833.517 km²' },
  UY: { capital: 'Montevideo', continent: 'América', population: '3.5M', area: '176.215 km²' },
  UZ: { capital: 'Taskent', continent: 'Asia', population: '35M', area: '448.978 km²' },
  VU: { capital: 'Port Vila', continent: 'Oceanía', population: '320K', area: '12.189 km²' },
  VA: { capital: 'Ciudad del Vaticano', continent: 'Europa', population: '800', area: '0.44 km²' },
  VE: { capital: 'Caracas', continent: 'América', population: '29M', area: '916.445 km²' },
  VN: { capital: 'Hanói', continent: 'Asia', population: '98M', area: '331.212 km²' },
  YE: { capital: 'Saná', continent: 'Asia', population: '33M', area: '527.968 km²' },
  ZM: { capital: 'Lusaka', continent: 'África', population: '19M', area: '752.618 km²' },
  ZW: { capital: 'Harare', continent: 'África', population: '16M', area: '390.757 km²' },
}